clc;
clf;
clear all;
N=input('enter no of samples:');
a=0.01;
n=0:0.1:N;
x=a.^n;
disp(x);
subplot(2,2,1);
plot2d3(n,x);
xlabel('time');
ylabel('amplitude');
title('exponential decaying signal response');
x1=a.^-n;
disp(x1);
subplot(2,2,2);
plot2d3(n,x1);
xlabel('time');
ylabel('amplitude');
title('exponential growing signal response');
