clc;
clf;
clear all;
x=input('enter the first sequence:');
y=input('enter the second sequence:');
n=convol(x,y);
subplot(2,2,1);
plot2d3(x);
title('first sequence');
xlabel('n');
ylabel('amp');
subplot(2,2,2);
plot2d3(y);
title('second sequence');
xlabel('n');
ylabel('amp');
subplot(2,2,3);
plot2d3(n);
title('convolved sequence');
xlabel('n');
ylabel('amp');
disp('the convolved sequence is');
disp(n);
